### ISSUE TITLE
读写ceph

### ISSUE THREAD

**Issue by sunxs1101** [k8sp/auto-install#108]
Client读写Ceph存储集群有两种路径：
 - 一种是利用QEMU走librbd路径，librbd是基于librados的更高层的块设备API实现，通过librbd创建一个块设备，rbd_aio_read()/rdb_aio_write()读写数据到osd，[官方步骤](http://docs.ceph.com/docs/master/rados/api/librados-intro/)，其中从mon机器中获取ceph.client.admin.keyring还可以通过读写etcd的方式来获取，因为在配置Ceph集群时，我们通过etcd的方式写入Ceph.conf中的配置信息。
 - 另一种是使用kernel module，走kernel的路径，linux内核在2.6.34以后集成了Ceph的模块，[官方文档](http://docs.ceph.com/docs/master/rbd/rados-rbd-cmds/)。

这两种方式前者主要为虚拟机提供块存储设备，后者主要为Host提供块设备支持。

**Comment by wangkuiyi** [comment]
@sunxs1101 QEMU是一个虚拟机软件，和Ceph有什么关系？你贴的“官方步骤” http://docs.ceph.com/docs/master/rados/api/librados-intro/ 里也没有提到QEMU。

**Comment by wangkuiyi** [comment]
issue的意思是“问题、毛病、麻烦事儿“。这个issue没有明确提出问题。相关描述也不够清晰。我把问题描述和背景描述在 https://github.com/k8sp/auto-install/issues/109 里了。可以把相关讨论挪过去。
