### ISSUE TITLE
cc server合并至bootstrapper

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/auto-install#116]
需要使cc server 服务以下静态文件：
- [x] install.sh, 访问url如: http://youserver.com/install.sh
- [x] CoreOS镜像, 访问url如: http://youserver.com/stable/1010.5.0/coreos_production_image.bin.bz2
- [x] 根据模版自动生成的cloud-config文件, 访问url如: http://yourserver.com/cloud-configs/08:00:36:a7:5e:9f.yaml
- [x] 自动生成的证书, ca.pem以及为api-server, worker, client生成的证书
- [x] 将Fixed IP修改为hostname
- [x] 替代Nginx的server static file功能

**Comment by Yancey1989** [comment]
Rename "cc server 合并至bootstrapper"
