### ISSUE TITLE
cc server如果指定了ca文件的路径，如果路径中没有文件也不会自动生成

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/auto-install#134]
cc server如果指定了ca文件的路径，如果路径中没有文件也不会自动生成
docker 中这样启动：
```
cloud-config-server -addr ":8081" \
  -dir /bsroot/html/static \
  -cc-template-file /bsroot/config/cloud-config.template \
  -cc-template-url "" \
  -cluster-desc-file /bsroot/config/cluster-desc.yml \
  -cluster-desc-url "" \
  -ca-crt /bsroot/tls/ca.pem \
  -ca-key /bsroot/tls/ca-key.pem &
```

/bsroot/tls目录存在，但下面没有文件。在访问：curl http://192.168.8.101:8081/cloud-config/08:00:27:ef:d2:12.yml报错：
```
open /bsroot/tls/ca.pem: no such file or directory
```
考虑这个是否需要改成自动生成，如果为了稳妥不自动生成，则在readme中说明

**Comment by Yancey1989** [comment]
关于证书的参数，按下面逻辑是否可以？

1. 不指定ca-key参数
  1. 自动生成ca-key和ca-crt

2. 指定ca-key参数,则cc server认为证书是已经存在的：
  1. 若指定文件不存在，则程序退出
  1. 若存在程序继续
