### ISSUE TITLE
去掉cluster-desc.yml中无用的fixedip配置

### ISSUE THREAD

**Issue by Yancey1989** [k8sp/auto-install#142]

**Comment by wangkuiyi** [comment]
这是因为使用dnsmasq之后，除了bootstrapper server之外的所有节点都用hostname标识，而不需要在配置里使用到IP地址了吗？

**Comment by Yancey1989** [comment]
是的，理论上来说boostrapper server也可以将本机的hostname注册到dns中，但为了实现简单还没加这一步骤。
