### ISSUE TITLE
如何使用内网ACI镜像？

### ISSUE THREAD

**Issue by Yancey1989** [k8sp/auto-install#28]
在启动kubernetes进程时，需要通过rkt启动ACI格式的hyperkube,flannel等镜像，而这个镜像地址默认是在公网quay.io上面，这会带来两个问题:

1. 外网下载速度太慢。
2. 安全原因，实际生产环境我们也不希望所有机器都有外网权限。

是否有搭建私有ACI仓库的方案或者其他解决此问题的方法呢？

**Comment by Yancey1989** [comment]
这样也需要从外网去下这些镜像，我在实验环境中尝试了如下方法:

1. 在一台能够连接外网的机器上用```rkt fetch <REMOTE URL>```的方式将hyperkube的ACI镜像下载到本地
2. 使用```rkt export <IMAGE NAME> <LOCAL FILE NAME>```将镜像保存在本地并上传至Nginx服务器
3. 在coreos机器上使用wget将镜像文件下载回来并使用```rkt fetch file://<LOCAL FILE PATH> --insecure-options=all```的方式将镜像保存在rkt 的image list中.

这里的```insecure-options=all```是说不使用签名机制，关于ACI的签名机制见链接：https://github.com/coreos/rkt/blob/master/Documentation/signing-and-verification-guide.md

**Comment by wangkuiyi** [comment]
谢谢 @Yancey1989 ！

这样是不是需要先ssh到机群里每一台机器，去执行 wget 和 rkt fetch？

rkt有没有类似Docker Hub的概念，从而可以配置一个rkt hub 服务器，并避免放在nginx上，而是可以直接跑那个里面的rkt镜像？

**Comment by Yancey1989** [comment]
* 我们的做法是在PXE Server上启一个Docker Registry服务，在CoreOS启动的CC文件中，先去通过 ```rkt fetch``` 获取ACI再去启动相关进程
* rkt目前来看没有类似Docker Hub的东西，不过可以从Docker Registry上获取Docker Image再转成ACI,链接:https://coreos.com/rkt/docs/latest/subcommands/fetch.html
* 在我们实验过程中发现即使通过VPN或者HTTP代理从Registry拉去镜像速度还是很慢，部署一台机器需要几十分钟，而使用private registry，部署一台机器只需要几十秒。我觉得为了加快这个速度，是否可以这样做：
    * PXE Server 上搭建Docker Registry，并将需要安装的镜像放在这个Registry中
    * 需要的二进制文件等放在Nginx的Static目录下
    * CoreOS启动的cc文件中从上述位置获取相关资源进行安装部署
@wangkuiyi 这样是否可以，我这边可以将这个实现做成PR提到这个项目中。
