### ISSUE TITLE
Necessary DHCP config items

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/auto-install#30]
@lipeng-unisound  以下这些DHCP配置项是必要的吗？

```
default-lease-time 600;
max-lease-time 7200;
authoritative;

option rfc3442-classless-static-routes code 121 = array of integer 8;

subnet 10.10.10.0 netmask 255.255.255.0 {
    option rfc3442-classless-static-routes 24, 192,168,6, 10,10,10,254, 24, 192,169,100, 10,10,10,254, 16, 10,200, 10,10,10,254;
}
```

**Comment by jiamliang** [comment]
我不太熟悉网络，对于这个设置，下面是我的理解：
在我们公司的内网里有多个网段。另外上海VPN到北京，从家里面VPN到北京公司，都会被分在不同的网段。为了使这些网段的主机之间能够进行通讯，需要配置一些路由规则。
如果不配置的话，这些网段里面的主机，就没法和机群所在的网段里面的主机进行通讯。

**Comment by wangkuiyi** [comment]
有一个比较灵活的办法：允许用户提供他自己的dhcp.conf 的 template，里面可以写很多比我们默认template更多的内容。如果用户不提供，则用我们默认的template。这样如何？
