### ISSUE TITLE
dhcpd nginx 这些服务的安装还是通过bash实现？

### ISSUE THREAD

**Issue by pineking** [k8sp/auto-install#41]
config文件夹下利用 go 生成 DHCP，nginx，PXE 的配置，通过 yaml 作为输入

欠缺一个串起来一键运行的 run.bash 在此bash里检测并安装 dhcpd nginx 等服务，并且利用 go 生成相关的配置

**Comment by wangkuiyi** [comment]
我的想法是全部都用Go写。这样可以吗？

**Comment by pineking** [comment]
可以
