### ISSUE TITLE
Proposal: configs是静态存储在github的，初始化新的集群需要修改代码中指向的config url

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/auto-install#43]
可以参考etcd的discovery服务：

1. 创建一个新的集群配置：使用ccts_client解析cluster的配置文件成json格式。发送POST请求到/new_cluster，POST body携带config的json
2. CCTS收到json，使用uuid4生成一个对应这个json的uuid作为唯一标示，并把uuid和json配置存储在etcd集群中
3. 配置集群PXE Server中的cloud-config文件，使用这个uuid请求CCTS获得本集群的config

这样，CCTS即可作为一个全局的config server

**Comment by wangkuiyi** [comment]
哪个程序把什么post给ccts呢？

**Comment by typhoonzero** [comment]
@wangkuiyi 的确需要一个client工具，将cluster的配置文件的yaml解析成json并post给CCTS

**Comment by Yancey1989** [comment]
根据我们目前的需求，每个PXE Server只对应一个集群，证书的生产可以在CCTS启动时一次性生成好，我觉得流程可以是这样：

1. 启动时生成CA Root```ca.pem, ca-key.pem```这两个文件
2. Node启时候，CCTS根据传来的MAC地址进行判断，master和worker节点返回不同的证书信息:
	* 如果为kube-master节点，则将```ca.pem, apiserver.pem, apiserver-key.pem```这三个文件的信息写入返回的cc文件中
	* 如果为kube-worker节点，则根据本地存储的```ca.pem, ca-key.pem```生成```worker-key.pem, worker.pem```写入返回的cc文件中

相关伪码如下:

1. 启动时候生成RootAC

```
func generateRootAC() {
	if fileExist("./tls/ca.pem") && fileExist("./tls/ca-key.pem") {
		fmt.Print("ca.pem has already exists.")
		return false
	}
	// Generate ca.pem, ca-key.pem located ./tls
	out, err := exec.Command("/bin/bash", "./script/generate_root_ca.sh").Output()
	if err != nil {
		fmt.Printf("Generate Root AC Failed: %s\n", out)
	}
}

```
2. 若请求的mac地址为kube-master节点，伪代码如下:

```
func processKubeMasterCert(ip string) bool {
	// Generate apiserver.pem, apiserver-key.pem located ./tls/master-${master_ip}/
	out, err := exec.Command("/bin/bash", "./script/generate_master_ca.sh", ip).Output()
	if err != nil {
		fmt.Printf("Generate Master AC Failed: %s\n", out)
		return false
	}
	return true
}
```
3. 若请求的mac地址为kube-worker节点，伪代码如下:

```
func processKubeNodeCert(ip string) {
	// Generate work.pem, work-key.pem located ./tls/work-${work_ip}/
	out, err := exec.Command("/bin/bash", "./script/generate_work_ca.sh". ip).Output()
	if err != nil {
		fmt.Printf("Generate Work AC Failed: %s\n", out)
		return false
	}
	return true
}
```

**Comment by typhoonzero** [comment]
更新：考虑到使用云端的存储来存放具有更高的可靠性，这里会稍作修改，增加一个可以修改server中的template_url和config_url的启动参数

**Comment by wangkuiyi** [comment]
怎么会需要一个client呢？我没有理解。

目前cloud-config-server的设计是通过wget/curl访问，url形式如下：
```
http://bootstrapper.company.com:9099?mac=aa-bb-cc-dd-ee-ff
```

**Comment by typhoonzero** [comment]
最上面的描述也可以不用看了。

核心的原因是：CCTS永远都是使用https://raw.githubusercontent.com/k8sp/auto-install/master/cloud-config-server/template/unisound-ailab/build_config.yml?token=ABVwec2SvquxRR_h9JF-9Rg8RvuuWjcpks5XnqyawA%3D%3D来初始化一个集群的。而这个配置在百分点可能完全不一样。如果要在百分点环境使用必须fork这个repo并commit代码，但这样云知声就没法用了。如果config和template是可以指定url的，就可以支持。

这个需求如果再通用，就需要有一个地方可以存储template和config，并根据一个id/token来访问
