### ISSUE TITLE
Docker 的 Ubuntu 14.04 image 存在 initctl 的问题

### ISSUE THREAD

**Issue by pineking** [k8sp/auto-install#68]
http://askubuntu.com/a/529693

http://stackoverflow.com/questions/28055715/running-services-upstart-init-d-in-a-container

导致通过 Upstart 创建的服务起不来，有点类似 CentOS的 systemctl的问题 https://github.com/k8sp/auto-install/issues/54

**Comment by wangkuiyi** [comment]
用VM代替Docker做测试 https://github.com/k8sp/auto-install/pull/81 希望能解决这个问题

**Comment by wangkuiyi** [comment]
Since https://github.com/k8sp/auto-install/pull/81, we have changed to use VM instead of Docker for OS-dependent testing.
