### ISSUE TITLE
vmtest/run 不能用public key登录CentOS guest

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/auto-install#92]
错误信息如下
```
default: Inserting generated public key within guest...
default: Removing insecure key from the guest if it's present...
default: Key inserted! Disconnecting and reconnecting using new SSH key...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
```
最后会询问用户名和密码。都输入vagrant就可以登录进去执行unit test了。

**Comment by wangkuiyi** [comment]
这是一个 vagrant 1.8.5 的 bug。按照 https://github.com/mitchellh/vagrant/issues/7610#issuecomment-234609660 的说法，已经在master branch上fix了。等到下一个版本 1.8.6发布的时候，就可以用了。

**Comment by jiamliang** [comment]
原来如此
LGTM

**Comment by wangkuiyi** [comment]
Need to change vmtest/run to overcome this problem.

**Comment by wangkuiyi** [comment]
Thinking about downgrading vagrant from 1.8.5 to 1.8.4, in order to escape from this bug.
