### ISSUE TITLE
flanneld 在所有node上还是在Kubernetes master nodes上？

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/auto-install#94]
我看到 @typhoonzero 的PR里把在每台机器上启动flanneld的逻辑改编成了只在Kubernetes master nodes上启动： https://github.com/k8sp/auto-install/pull/64/files#r73539623

因为我对flanneld了解不够，又因为为了每个PR目标单纯所以从上面PR里把这个修改给去掉了，所以还得请大家注意可能要在另一个PR里加入这个修改。

**Comment by pineking** [comment]
https://coreos.com/kubernetes/docs/latest/deploy-workers.html#start-kubelet-flannel-and-calico-node  从这个链接来看， worker node 也需要启动 flanneld吧

**Comment by typhoonzero** [comment]
每个节点是都需要启动flanneld，但设置etcd的/coreos.com/network/config只需要设定一次就行。我也还不确定是否每次执行etcdctl set命令，是否回触发所有的etcd更新配置，但理论上，worker不应该负责设置整个集群的网段信息。

这样还有另一个问题，就是master必须先于worker完成初始化

**Comment by pineking** [comment]
对的，worker不需要设置网段信息，在master搞下就可以了
